### ISSUE TITLE
CPF mask="999.999.999-99 Error

### ISSUE THREAD

**Issue by rogerin** [tiaguinho/ionic2-mask-directive#2]
<ion-input id="cpf" mask="999.999.999-99" name="cpf" type="text"  [(ngModel)]="cpf" placeholder="CPF"></ion-input>

Runtime Error
Cannot read property 'match' of undefined

Stack
TypeError: Cannot read property 'match' of undefined
    at Ionic2MaskDirective.format (http://localhost:8100/build/vendor.js:117390:24)
    at Ionic2MaskDirective.onKeyUp (http://localhost:8100/build/vendor.js:117385:48)
    at Object.eval [as handleEvent] (ng:///AppModule/SignUpPage.ngfactory.js:937:43)
    at Object.handleEvent (http://localhost:8100/build/vendor.js:12273:138)
    at Object.handleEvent (http://localhost:8100/build/vendor.js:12976:85)
    at dispatchEvent (http://localhost:8100/build/vendor.js:9173:21)
    at http://localhost:8100/build/vendor.js:9765:20
    at HTMLElement.<anonymous> (http://localhost:8100/build/vendor.js:74228:53)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9655)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4499:37)

Ionic Framework: 3.5.0
Ionic App Scripts: 2.0.0
Angular Core: 4.1.3
Angular Compiler CLI: 4.1.3
Node: 6.11.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

**Comment by rogerin** [comment]
I used the keyboard tab tab to test, so it gives this error.

**Comment by rogerin** [comment]
MacBook-Pro-de-Rogerio:ibolttapp rogerio$ ionic cordova build ios --prod
? Looks like a fresh checkout! No ./node_modules directory found. Would you like to install project dependen
cies? Yes
[INFO] Installing dependencies may take several minutes!
> npm install
✔ Running command - done!
Running app-scripts build: --prod --iscordovaserve --externalIpRequired --nobrowser

[21:03:44]  build prod started ...
[21:03:44]  clean started ...
[21:03:44]  clean finished in less than 1 ms
[21:03:44]  copy started ...
[21:03:44]  ngc started ...
[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins
       may be out of date.
Error: Unexpected value 'Ionic2MaskDirective in /Users/rogerio/Documents/ChegaJa/iboltt/ibolttapp/node_modules/ionic2-mask-directive/index.d.ts' declared by the module 'AppModule in /Users/rogerio/Documents/ChegaJa/iboltt/ibolttapp/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.

**Comment by tuliogalli** [comment]
Hi, i have same problem.

Thanks and congratulations for the project.


    @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.3
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.6.0

System:

    Android SDK Tools : 26.0.2
    ios-deploy        : 1.9.1 
    Node              : v6.11.1
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b
